# Generated by Django 2.1 on 2025-10-07 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('incident_type', models.CharField(choices=[('flood', 'Flood'), ('drought', 'Drought'), ('algal bloom', 'Algal Bloom'), ('contaminated water', 'Contaminated Water'), ('hydroelectric disruption', 'Hydroelectric Disruption'), ('invasive species', 'Invasive Species'), ('declining fish population', 'Declining Fish Population')], max_length=50)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('suspected', 'Suspected')], max_length=20)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('geometry', jsonfield.fields.JSONField(default=dict)),
                ('properties', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('population_2021', models.IntegerField(default=0)),
                ('geometry', jsonfield.fields.JSONField(default=dict)),
                ('properties', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('management', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('park_class', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('geometry', jsonfield.fields.JSONField(default=dict)),
                ('properties', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='geojson_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('incidents_added', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
